pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri('https://nexus-external.vkteam.ru/repository/maven/') }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri('https://nexus-external.vkteam.ru/repository/maven/') }
    }
}
rootProject.name = "SixA9AGuide"
include ':app'
